Header components
mesg-foundation/mesg-components pull request #59
Opened 2019-10-18 04:34 UTC by blackinno

- revers header component

2019-10-18 07:03 UTC, antho1404 requested changes

2019-10-18 07:03 UTC, antho1404 commented on packages/Header/Header.vue
> +  <div id="header" pt3 pb3 mb3>
Same comment about the attributes `ptX`, `pbX`... than https://github.com/mesg-foundation/mesg-components/pull/58/files#r336343955

2019-10-18 07:03 UTC, antho1404 commented on packages/Header/Header.vue
> +    noPicture: { type: Boolean, default: false },
`noPicture` could be computed based on `imgUrl` presence.
Also, one is img, the other one picture. We need consistency either both img or both picture but let's not mix

2019-11-14 03:46 UTC, blackinno commented
https://github.com/mesg-foundation/mesg-components/issues/67

2019-11-14 04:25 UTC, antho1404 approved these changes
Good for me, @EmmanuelDrouin can you check and merge if the design is fine

2019-11-14 10:45 UTC, EmmanuelDrouin commented
@blackinno Can you remove the display flex on the slot? Because of the display flex the button is taking the full width of the container but it shouldn't.

2019-11-15 04:48 UTC, EmmanuelDrouin commented
Good for me, will merge this PR

2019-11-15 04:48 UTC, merged